project_id = "llcvudydgizzuqctatnt"

[functions.bootstrap-admin]
verify_jwt = false

[functions.impersonate-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.send-hrm-email]
verify_jwt = false

[functions.scheduled-backup]
verify_jwt = false

[functions.restore-backup]
verify_jwt = false

[functions.factory-reset]
verify_jwt = true

[functions.mark-absent-employees]
verify_jwt = false

[functions.backfill-absent-records]
verify_jwt = false
