import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Share2, FileSpreadsheet, FileText } from 'lucide-react';
import { WhatsAppShareModal } from './WhatsAppShareModal';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';

interface ReportActionsProps {
  reportTitle: string;
  staffName: string;
  dateFrom: Date;
  dateTo: Date;
  summaryData: Record<string, string | number>;
  tableHeaders: string[];
  tableData: Array<Record<string, any>>;
}

export function ReportActions({
  reportTitle,
  staffName,
  dateFrom,
  dateTo,
  summaryData,
  tableHeaders,
  tableData,
}: ReportActionsProps) {
  const [showWhatsApp, setShowWhatsApp] = useState(false);

  const dateFromStr = format(dateFrom, 'yyyy-MM-dd');
  const dateToStr = format(dateTo, 'yyyy-MM-dd');
  const fileBaseName = `vakari-${reportTitle.toLowerCase().replace(/\s+/g, '-')}-${staffName.toLowerCase().replace(/\s+/g, '-')}-${dateFromStr}-${dateToStr}`;

  const downloadCSV = () => {
    // Build CSV content
    const summaryRows = Object.entries(summaryData).map(([key, value]) => 
      `"${key}","${value}"`
    );
    
    const headerRow = tableHeaders.map(h => `"${h}"`).join(',');
    const dataRows = tableData.map(row => 
      tableHeaders.map(h => {
        const key = h.toLowerCase().replace(/[^a-z0-9]/g, '');
        const value = row[key] ?? row[h] ?? '';
        return `"${value}"`;
      }).join(',')
    );

    const csv = [
      `"${reportTitle}"`,
      `"Staff: ${staffName}"`,
      `"Period: ${format(dateFrom, 'dd MMM yyyy')} - ${format(dateTo, 'dd MMM yyyy')}"`,
      '',
      '"Summary"',
      ...summaryRows,
      '',
      '"Daily Breakdown"',
      headerRow,
      ...dataRows,
    ].join('\n');

    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileBaseName}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(18);
    doc.text(reportTitle, 14, 20);
    
    // Subtitle
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Staff: ${staffName}`, 14, 28);
    doc.text(`Period: ${format(dateFrom, 'dd MMM yyyy')} - ${format(dateTo, 'dd MMM yyyy')}`, 14, 34);
    
    // Summary section
    doc.setFontSize(13);
    doc.setTextColor(0);
    doc.text('Summary', 14, 46);
    
    let yPos = 52;
    doc.setFontSize(10);
    Object.entries(summaryData).forEach(([key, value]) => {
      doc.text(`${key}: ${value}`, 14, yPos);
      yPos += 6;
    });
    
    // Table
    yPos += 10;
    doc.setFontSize(13);
    doc.text('Daily Breakdown', 14, yPos);
    
    autoTable(doc, {
      startY: yPos + 6,
      head: [tableHeaders],
      body: tableData.map(row => 
        tableHeaders.map(h => {
          const key = h.toLowerCase().replace(/[^a-z0-9]/g, '');
          return row[key] ?? row[h] ?? '';
        })
      ),
      styles: { fontSize: 8 },
      headStyles: { fillColor: [59, 130, 246] },
    });
    
    // Footer
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Generated by Vakari Vision on ${format(new Date(), 'dd MMM yyyy HH:mm')}`,
        14,
        doc.internal.pageSize.height - 10
      );
    }
    
    doc.save(`${fileBaseName}.pdf`);
  };

  // Build WhatsApp message
  const whatsAppMessage = [
    `*${reportTitle}*`,
    `Staff: ${staffName}`,
    `Range: ${format(dateFrom, 'dd MMM yyyy')} - ${format(dateTo, 'dd MMM yyyy')}`,
    '',
    ...Object.entries(summaryData).map(([key, value]) => `${key}: ${value}`),
    '',
    '_(Auto-generated from Vakari Vision)_',
  ].join('\n');

  return (
    <>
      <div className="flex items-center gap-2">
        <Button variant="outline" size="sm" onClick={downloadCSV}>
          <FileSpreadsheet className="w-4 h-4 mr-2" />
          CSV
        </Button>
        <Button variant="outline" size="sm" onClick={downloadPDF}>
          <FileText className="w-4 h-4 mr-2" />
          PDF
        </Button>
        <Button variant="outline" size="sm" onClick={() => setShowWhatsApp(true)}>
          <Share2 className="w-4 h-4 mr-2" />
          WhatsApp
        </Button>
      </div>

      <WhatsAppShareModal
        open={showWhatsApp}
        onOpenChange={setShowWhatsApp}
        reportTitle={reportTitle}
        dateFrom={dateFrom}
        dateTo={dateTo}
        message={whatsAppMessage}
      />
    </>
  );
}
